import React from "react";
import "./globals.css";
import {Inter} from "next/font/google";
import PropTypes from "prop-types";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "City Furnish",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
RootLayout.propTypes = {
  children: PropTypes.element,
};
